root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run ./cmd/api/main.go migrate up"

  delay = 1000

  kill_timeout = 5

  include_ext = ["go", "tpl", "tmpl", "html"]

  exclude_dir = ["vendor", "tmp", ".git", "front-end"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
